### PR TITLE
MM-12841 Fix for mention channel ordering with unread channels

### PR DESCRIPTION
**Pull request by sudheerDev**
#### Summary
Sorting for unreads with muted channels should follow this order

1. If muted channels have unreads mentions they should be sorted to be at the end of mention channels
2. If multiple muted channels have mentions they should be sorted alphabetically at the bottom of mention channels list 

#### Ticket Link
[MM-12841](https://mattermost.atlassian.net/browse/MM-12841)
[MM-12841](https://mattermost.atlassian.net/browse/MM-12638)

nov-01-2018 14-07-00

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit tests passed
- [x] Ran `make flow` to ensure type checking passed
- [x] Added or updated unit tests (required for all new features)

### CODE REVIEW

**Comment by sudheerDev** [comment]
@enahum Yes, i would have to update mm-redux hash for webapp master and release branches and same for mobile.

**Comment by sudheerDev** [comment]
@enahum Yes, i would have to update mm-redux hash for webapp master and release branches and same for mobile.

**Comment by hmhealey** [comment]
@sudheerDev Make sure you're careful to have everything point to the right place when you're cherry-picking so that the apps point to the correct branches of the redux repo depending on for the master and release branches

**Comment by DHaussermann** [comment]
@sudheerDev This changes the behavior not only for when channels are selected but for how they are sorted in general. Previously muted channels with mentions would always be at the bottom of unreads. I think this was the expected behavior. Can we double check with a PM before making this change?

Before: 
channelsortbefore

After:
channelsortafter

**Comment by enahum** [comment]
Actually Dylan is right, muted channels should be sorted at the end

**Comment by sudheerDev** [comment]
@DHaussermann yes, These changes were discussed with @esethna 

@enahum As of now muted channels are not at the bottom of unread mentions list. They are sorted alphabetically and can stay in the middle as in the screenshots of the actual issue posted in the ticket.
You might be referring to the muted unread channels(not mentions) where they stay in the list at the bottom(Not in unread sections)

@esethna To confirm the changes

**Comment by sudheerDev** [comment]
@enahum I don't see muted unreads at the bottom when i test on CI 

screenshot 2018-11-02 at 3 25 42 am

**Comment by esethna** [comment]
Muted channels appear at the bottom of all sections when the unreads feature was turned off. With it on, I don't think muted channels ever sorted correctly in the unreads section, **when they have mentions** (they seemed to sort randomly for me when I tested it)

**Comment by esethna** [comment]
So the change here is to sort muted channels at the bottom of the unreads section unless they have mentions, in which case sort them at the bottom of the channels with mentions in the unreads section

**Comment by DHaussermann** [comment]
Thanks @esethna . The change to list muted channels with a mentions at the bottom of mentions now makes sense. To clarify on one thing... your comment above said "bottom of the unreads section" for when there is no mention.

Since muted channels are never shown as "unread" without a mention, they will either sort to the bottom the mentions (new behavior) or be listed at the bottom of the appropriate section with the **read** channels.

Please correct me if I have misunderstood anything :)

**Comment by DHaussermann** [comment]
Unread sorting seems be working exactly as expected. I have tested with all applicable channel types.  Testing is ongoing. I will play with a bit more data to see if I can find any weird behavior when opening the unread channels.

**Comment by esethna** [comment]
^ yes you're correct, thanks Dylan.

**Comment by DHaussermann** [comment]
@sudheerDev this looms good.

- Tested sorting rules for unread - including with and without mention and muted / unmuted 
- Tested sorting rules for read- including muted / unmuted 
- Did various test of reading different unread channels (channel type, mute/unmute, mention/no mention)
- Read unread channels with different types of data in the sidebar (Channel types, Mutted status, mention status)
- Tested channels moving from unread to mentions based on data in the channel changing.

I could no longer repo the bug where muted mentions cause sorting issues with unread or any other sorting irregularities

Added test scenarios to JIRA task.

**Comment by sudheerDev** [comment]
Thanks @DHaussermann

**Pull request merged**
