### PR TITLE
Modify channel utils to include group messages

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
Includes GM channels to the list and sort favorites excluding the type of channel

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-5721
https://mattermost.atlassian.net/browse/PLT-5888

#### Test Information
This PR was tested on: IOS 10.2.1 iPhone 6s, Android 6.0.1 Samsung J5

### CODE REVIEW

**Comment by jwilander** [comment]
If you load the app and one of your hidden GMs has an unread, will it show up in the LHS? Assuming the message was received while you weren't connected to the websocket

**Comment by enahum** [comment]
Good question, haven't tried that will do

**Comment by enahum** [comment]
actually its not even happening with DM's

**Comment by enahum** [comment]
@jwilander done my friend

**Pull request merged**
