### PR TITLE
[MM-9516] Add new ephemeral post as EPHEMERAL_ADD_TO_CHANNEL

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Add new ephemeral post as EPHEMERAL_ADD_TO_CHANNEL
- This is an ephemeral post at Thread of mobile app (or RHS on webapp) after a user has been added thru at-mention.

#### Ticket Link
Jira ticket: [MM-9516](https://mattermost.atlassian.net/browse/MM-9516)

#### Checklist
- [x] Added or updated unit tests (required for all new features)

### CODE REVIEW

**Comment by jwilander** [comment]
Little confused as to why this is needed, could you provide a bit more clarification? I just ask because we have this feature on the web app and I don't see us using a special type there

**Comment by saturninoabril** [comment]
Primary reason was that mobile app is using most of the constant from `mattermost-redux` such as those in `Posts.POST_TYPES`. I just thought that it may be better to add `EPHEMERAL_ADD_TO_CHANNEL` here. Then since it's here now, I added that to `isPostEphemeral` to centralize the use of that function. We can use it for webapp as well in the near future.

**Comment by jwilander** [comment]
Ok sounds good

**Comment by saturninoabril** [comment]
Cool, thanks!

**Pull request merged**
