### PR TITLE
Fix dependencies for react native app #978

### LINKED ISSUE #978: Running React Native app with mattermost-redux fails.
#### Summary
Running React Native app with mattermost-redux fails.

#### Steps to reproduce
- npm i  mattermost-redux --save
- react-native run-ios

####  Expected behavior
The React Native app should start without error.

#### Observed behavior

> error: bundling failed: Error: Unable to resolve module `core-js/modules/web.dom-collections.iterator` from `/Users/node_modules/mattermost-redux/store/configureStore.dev.js`: Module `core-js/modules/web.dom-collections.iterator` does not exist in the Haste module map

####  Possible fixes
Install additional deps
- @react-native-community/netinfo
- core-js
- remote-redux-devtools

### PR DESCRIPTION
**Pull request by avegrv**
#### Summary
Fix #978, moved core-js from devDeps to deps

#### Ticket Link
#978

#### Test Information
This PR was tested on: [MacOS, 10.13.6]

### CODE REVIEW

**Comment by jasonblais** [comment]
Thanks @avegrv for the contribution! Would you be open to help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)? If you have any questions, don't hesitate to ask!

cc @lindalumitchell on QA review

**Comment by lindalumitchell** [comment]
Thanks Jason! @avegrv @jespino @crspeller any guidance for what QA should test for these changes? Is this something that test builds can be built for from this PR, or is it different because it's a dependency update?

**Comment by avegrv** [comment]
@lindalumitchell 

> any guidance for what QA should test for these changes? Is this something that test builds can be built for from this PR, or is it different because it's a dependency update?

It's just a dependency update, Thank you.

**Comment by hanzei** [comment]
@jespino Could you help resolving the CI failure?	
 ```
> eslint --ignore-path .gitignore --ignore-pattern node_modules --quiet 'src/**/*.ts'

sh: 1: eslint: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! mattermost-redux@5.3.1 check: `eslint --ignore-path .gitignore --ignore-pattern node_modules --quiet 'src/**/*.ts'`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the mattermost-redux@5.3.1 check script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2019-12-11T10_13_54_804Z-debug.log
```
https://app.circleci.com/jobs/github/mattermost/mattermost-redux/2483

**Comment by hanzei** [comment]
Thanks for fixing this @avegrv :+1:

**Pull request merged**
