### PR TITLE
[GH-1290] Update isomorphic-fetch to 3.0.0 and make it a dev dependency

### PR DESCRIPTION
**Pull request by sbley**
#### Summary
This pull request updates to the latest version of isomorphic-fetch (3.0.0) which resolves a security vulnerability. It also moves isomorphic-fetch to the devDependencies because the library is only used for testing purposes.

#### Ticket Link
  Fixes https://github.com/mattermost/mattermost-redux/issues/1290

### CODE REVIEW

**Review by hmhealey — APPROVED** [review]
Thanks for the PR! Looks good to me

**Review by Willyfrog — APPROVED** [review]
LGTM! thanks for making mattermost a bit safer :D

**Comment by Willyfrog** [comment]
@hmhealey this doesn't need QA review, right? I see it was moved to devdependencies

**Comment by hmhealey** [comment]
Yeah, that's correct. It's only used for unit tests.

**Pull request merged**
