### PR TITLE
add new field in userstatus type

### PR DESCRIPTION
**Pull request by darkLord19**
Redux changes for mattermost/mattermost-server#15640 and mattermost/mattermost-server#16067

### CODE REVIEW

**Review by reflog — APPROVED** [review]
LGTM

**Comment by reflog** [comment]
Do not merge until https://github.com/mattermost/mattermost-server/pull/16067 is done

**Review by hmhealey — APPROVED** [review]
Looks good assuming the model doesn't need to change on the server

**Comment by hmhealey** [comment]
Webapp PR: https://github.com/mattermost/mattermost-webapp/pull/7037

**Comment by hmhealey** [comment]
@darkLord19 We're going to be shortly deprecating mattermost-redux as a standalone repository and moving it into [mattermost-webapp](https://github.com/mattermost/mattermost-webapp) as part of an effort to make development of both codebases easier by using a monorepo. This is going to require either merging or closing all outstanding pull requests in this repository in preparation for the migration planned for tomorrow.

For this PR, it looks like it can't be merged into master immediately because it will require changes in the web app to add the new field to existing objects, so it'll have to be closed and resubmitted against mattermost-webapp separately. You can do that yourself if you'd like, or we could help with that instead. The easiest way to do that would probably be to integrate them into https://github.com/mattermost/mattermost-webapp/pull/7037 after the migration is done.

**Comment by darkLord19** [comment]
@hmhealey thanks for the heads up. If you need you can close this PR. I will raise new PR against webapp repo.

**Comment by hmhealey** [comment]
I'll let you know when that can be done. The migration is a bit behind schedule, but it will still be happening in the next day or two.

**Comment by hmhealey** [comment]
@darkLord19 Thanks for waiting on that. mattermost-redux now lives [here](https://github.com/mattermost/mattermost-webapp/tree/master/packages/mattermost-redux), so you can add these changes to your webapp PR.

**Pull request closed without merging**
