### PR TITLE
PLT-8532: Select correctly the last user post in a channel

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
Select correctly the last user post (system and ephimeral messages are ignored)

#### Ticket Link
[PLT-8532](https://mattermost.atlassian.net/browse/PLT-8532)

#### Test Information
This PR was tested on: Linux Firefox 57.0.3

### CODE REVIEW

**Comment by enahum** [comment]
@hmhealey can you update to the latest mattermost-redux in your https://github.com/mattermost/mattermost-mobile/pull/1344 PR once this goes in?

**Comment by hmhealey** [comment]
@enahum I'd rather not add unrelated changes to that PR. I also don't think this change will affect the mobile app since this selector isn't used there

**Comment by enahum** [comment]
If i’m correct we use the selector to get the post when adding a reaction with +:emoji:

**Comment by enahum** [comment]
But maybe im confused with another selector

**Comment by jespino** [comment]
i think it needs to be a PR to webapp-4.6. Right?

**Comment by jespino** [comment]
Finally I moved the PR to the webapp-4.6 branch

**Pull request merged**
