### PR TITLE
Get the total count of system users from the api endpoint /users/stats

### PR DESCRIPTION
**Pull request by lisakycho**
#### Summary
Passes the number of total users to mattermost-webapp.

#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/6521

### CODE REVIEW

**Comment by hmhealey** [comment]
You've got some style issues here that is preventing the PR from being built
```
> mattermost-redux@1.2.0 check /home/ubuntu/jenkins/workspace/mmrdx/mattermost-redux-pr/src/github.com/mattermost/mattermost-redux
> eslint --ignore-path .gitignore --ignore-pattern node_modules --quiet .


/home/ubuntu/jenkins/workspace/mmrdx/mattermost-redux-pr/src/github.com/mattermost/mattermost-redux/src/reducers/entities/users.js
  401:1  error  Trailing spaces not allowed  no-trailing-spaces

/home/ubuntu/jenkins/workspace/mmrdx/mattermost-redux-pr/src/github.com/mattermost/mattermost-redux/src/store/initial_state.js
  337:29  error  Trailing spaces not allowed  no-trailing-spaces

✖ 2 problems (2 errors, 0 warnings)
  2 errors, 0 warnings potentially fixable with the `--fix` option.
```

**Comment by lisakycho** [comment]
hey, @hmhealey! I fixed the style issues, please let me know if there is anything else!

**Comment by hmhealey** [comment]
Waiting on https://github.com/mattermost/mattermost-server/pull/8847 to be merged after 5.0 is branched

**Comment by cpanato** [comment]
hello @lisakycho can you please rebase and fix the conflict? thanks!

**Comment by hmhealey** [comment]
@lisakycho The server PR for this has been merged, so if you rebase this, we can get it merged as well

**Comment by enahum** [comment]
is this still a valid PR? if so it needs rebase

**Comment by lisakycho** [comment]
@enahum, @hmhealey sorry for the late reply, this has been rebased!

**Pull request merged**
