### PR TITLE
Add actions to save/delete theme preference

### PR DESCRIPTION
**Pull request by cometkim**
#### Summary

This is a migration PR for https://github.com/mattermost/mattermost-webapp/pull/2679

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit tests passed
- [x] Ran `make flow` to ensure type checking passed
- [x] Added or updated unit tests (required for all new features)

### CODE REVIEW

**Comment by enahum** [comment]
Wondering if these functions should be part of the webapp instead of having them in this repo.

Thoughts?

**Comment by jwilander** [comment]
Themes work for mobile right? Why would these just be in the web app?

**Comment by enahum** [comment]
They do work on mobile but if I'm not mistaken it makes use of `savePreferences` directly.

I'm ok having this here and then changing the code in the mobile app to make use of it.

**Comment by cometkim** [comment]
I think saveTheme here is fine. It's a simple wrapper of savePreferences with a side effect and having this in webapp would make a circular dependency.

**Comment by cometkim** [comment]
Yep, sure thing.

**Pull request merged**
