### PR TITLE
Fix createComplianceReport action parameter type

### PR DESCRIPTION
**Pull request by daniel-shuy**
#### Summary

The `mattermost-server` [POST `/compliance/reports`] (https://github.com/mattermost/mattermost-server/blob/v5.28.1/api4/compliance.go#L23) API expects a [Compliance](https://github.com/mattermost/mattermost-server/blob/v5.28.1/model/compliance.go#L24) (see [ComplianceFromJson()](https://github.com/mattermost/mattermost-server/blob/v5.28.1/model/compliance.go#L101)), but the `mattermost-redux` [createComplianceReport()](https://github.com/mattermost/mattermost-redux/pull/1289/files#diff-4858c6eaa6b8141168b93baf130f295640fa0a66fdf3d6174dba2e4315cb707dL133) action takes in a [Job](https://github.com/mattermost/mattermost-redux/blob/b928ae9d0bed614138a020b405f4bffd5143d54c/src/types/jobs.ts#L6) instead of a [Compliance](https://github.com/mattermost/mattermost-redux/blob/b928ae9d0bed614138a020b405f4bffd5143d54c/src/types/compliance.ts).

### CODE REVIEW

**Review by hahmadia — APPROVED** [review]
Nice catch! Good fix. Thanks

**Review by mkraft — APPROVED** [review]

**Comment by jgilliam17** [comment]
@jfrerich Is there a way to create a test server for redux pr? Od should I test this after merge? Thanks.

**Comment by jfrerich** [comment]
Personally, I think this is fine to test post merge.  I'm not positive how one would create a test server for a redux PR

**Review by jgilliam17 — APPROVED** [review]
Thank you @daniel-shuy
Approving - QA will test this after merge.

**Comment by jasonblais** [comment]
@jfrerich or @hanzei are you open to help with merging this PR? Thanks!

**Pull request merged**
