### PR TITLE
Enable gitlab ci for release-5.29

### PR DESCRIPTION
**Pull request by metanerd**

### CODE REVIEW

**Comment by sbley** [comment]
Hi @metanerd, may I ask if you are also going to release 5.31 within the next days?

**Comment by metanerd** [comment]
Hi @sbley! I am planning to, but I cannot promise anything.

**Comment by metanerd** [comment]
@sbley I released 5.31.

**Comment by sbley** [comment]
Thank was quick. Thank you!

**Comment by sbley** [comment]
HI @metanerd I noticed the 5.31 release does not contain type definitions and js files but only the `src` folder itself. Is that on purpose or was there a problem with publishing? Should I file an issue for that?

**Comment by metanerd** [comment]
I am going to investigate. Thank you for your report!

**Comment by ujaehnic** [comment]
Hi @metanerd, additionally it seems release 5.31.0 does not contain the fix for issue #1290 or did I just missed something?

**Pull request merged**
