### PR TITLE
Fix "{yyyy} {name of copyright owner}" in LICENSE.txt

### PR DESCRIPTION
**Pull request by jasonblais**

### CODE REVIEW

**Comment by jasonblais** [comment]
@enahum It's 2016 in the License header.

Though that said, I'm actually not sure if it should be 2016 or "2016-present"

**Comment by enahum** [comment]
@jasonblais it should be `Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.` as well as in the header

**Comment by jasonblais** [comment]
Changed it to "2016-present" since this project was created in 2016,

**Comment by enahum** [comment]
This is a file in this project https://github.com/mattermost/mattermost-redux/blob/master/src/client/client4.js#L1 as any other file in this project is 2015-present

**Comment by jasonblais** [comment]
Sure, though I still think it should be 2016-present in all headers then,

**Pull request merged**
