### PR TITLE
MM-15751 Fix for system messages not rendering in IE

### PR DESCRIPTION
**Pull request by sudheerDev**
#### Summary
  * Export constants COMBINED_USER_ACTIVITY_PREFIX and MAX_COMBINED_SYSTEM_POSTS
    from posts constants file for usage in webapp

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-15751

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit tests passed
- [x] Ran `make flow` to ensure type checking passed
- [x] Added or updated unit tests (required for all new features)

### CODE REVIEW

**Comment by hmhealey** [comment]
Do we have to move those constants to `constants/posts`? The files in `constants` are full of random, unrelated values, so I left `COMBINED_USER_ACTIVITY` in that file because it'll always be used with the other values in that file.

**Comment by sudheerDev** [comment]
@hmhealey Not really but if i am going to use it in webapp i felt we should move to constants. If in the previous file i doubt if it would be obvious that it is being used in webapp and might cause an issue if removed.

**Comment by hmhealey** [comment]
I think we should keep them all in `utils/post_list` since that's where they're used. It doesn't make sense to have them in separate files when you'd want to use them together anyway

**Comment by sudheerDev** [comment]
@hmhealey I am going to use these in https://github.com/mattermost/mattermost-webapp/pull/2865 so moving them to constants file. Sorry i am not sure if you had noticed it. You still want to keep them in the same file even if i am going to use them in webapp?

**Comment by hmhealey** [comment]
Yeah, I'd prefer to keep them in the same place. The other constants that are exported from that file are also used in the web app

**Comment by sudheerDev** [comment]
@hmhealey make changes but it seems odd that we want to keep constants in the file and export them when using in different repos. I feel we should be keeping them in constants file if we use them in different repos

> Re: The files in constants are full of random, unrelated values

Sounds like a tech debt ticket but if we don't keep them in constants file then cleaning up after these later will be even harder.

So i propose that we keep constants in file if we use only use in the repo and keep them in constants file if we use them across repos.

**Comment by hmhealey** [comment]
Thanks for moving those back. I think using the constants file makes sense for more general values (like action types or file extensions), but for things like this where the code is tightly coupled to the constants, I think they should stay together

**Pull request merged**
