### PR TITLE
MM-20272 Prevent channel reducers from deleting the active channel.

### PR DESCRIPTION
**Pull request by crspeller**
- Prevents the active channel from being removed from the channels list. 
- Fixes and issue where fetching of channels on focus change would cause your view of an archived channel to crash.

### CODE REVIEW

**Comment by crspeller** [comment]
@jespino Ya. Worried about side effects myself. Added a test, but it not working is not what I am worried about with this PR.

**Comment by lindy65** [comment]
Thanks @crspeller - this will be tested post-merge 👍

**Comment by amyblais** [comment]
@jespino @sudheerDev Kind reminder to review this for 5.18.

**Comment by amyblais** [comment]
@crspeller This hasn't been cherry-picked yet.

**Comment by crspeller** [comment]
@amyblais Done. Thanks for the reminder.

**Pull request merged**
