### PR TITLE
MM-30087 Remove direct dependency between Client4 and Rudder

### PR DESCRIPTION
**Pull request by hmhealey**
We had a report of a user not being able to use Client4 in a Node environment because of some weirdness from importing Rudder, so this separates Rudder from Client4. There's an accompanying webapp PR that will have the webapp use `Client4.setTelemetryHandler` to enable in the same place that it would've before.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-30087

#### Related Pull Requests
https://github.com/mattermost/mattermost-webapp/pull/7056

### CODE REVIEW

**Review by reflog — APPROVED** [review]
LGTM

**Review by sudheerDev — APPROVED** [review]
LGTM

**Comment by hmhealey** [comment]
Needs to be tested on the accompanying webapp PR

**Review by jgilliam17 — APPROVED** [review]
Thank you @hmhealey 
 QA will test after merge.

**Pull request merged**
