### PR TITLE
Add initial state directly into service layer

### PR DESCRIPTION
**Pull request by jwilander**
#### Summary
Add the initial state here so that the users of the service don't need to worry about any of the internal reducers when initializing state. They still have the option to override if they choose to.

### CODE REVIEW

**Comment by jwilander** [comment]
I haven't tried it but I can't see why it wouldn't

**Comment by enahum** [comment]
Try it out to see, maybe ask @jarredwitt as I know it was causing issues in the past

**Comment by jwilander** [comment]
Which part of this PR are you talking about? The initial state bit or the npm/babel changes?

**Comment by enahum** [comment]
Npm babel

**Comment by jwilander** [comment]
This repo shouldn't be using anything react native specific, otherwise the whole point of it is moot. If there's issues on RN because of that we can deal with those when we move it over to `master`

**Comment by enahum** [comment]
Then we need to figure out a way not to transpile this on post-install

**Comment by jwilander** [comment]
Sorry @enahum, I just pushed another commit. I've been using this branch with my work for the webapp :P

**Pull request merged**
