### PR TITLE
Replace Jenkins to use circleci

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
Replace Jenkins to use circleci for PRs

### CODE REVIEW

**Comment by cpanato** [comment]
getting this error
```
FAIL  src/actions/alerts.test.js
  ● Test suite failed to run

    ENOMEM: not enough memory, read

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:423:43)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:493:19)
      at Object.<anonymous> (node_modules/expect/build/index.js:9:43)

```

a lot of tests is failing with this error

**Comment by cpanato** [comment]
fixed defining the maxWorkers

**Comment by cpanato** [comment]
ping @grundleborg @jwilander

**Comment by jwilander** [comment]
Waiting for the discussion in the developer meeting first to make sure there are no objections

**Comment by cpanato** [comment]
no objections @jwilander ;)

**Comment by cpanato** [comment]
@grundleborg ptal

**Pull request merged**
