### PR TITLE
PLT-6403: Add post action endpoint

### PR DESCRIPTION
**Pull request by ccbrown**
#### Summary
See https://github.com/mattermost/platform/pull/7274

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-6403

#### Checklist
- [x] Added or updated unit tests (required for all new features)
- [x] All new/modified APIs include changes to the drivers

#### Test Information
This PR was tested on: MacOS Chrome

### CODE REVIEW

**Comment by ccbrown** [comment]
@enahum see https://github.com/mattermost/platform/pull/7274

**Comment by ccbrown** [comment]
@enahum I'm not really sure if I should add an action. Maybe I should? I just added what was necessary for the other PR.

**Comment by enahum** [comment]
@ccbrown I would probably create an action to avoid calling the client directly, that way it stays consistent with other API calls and I would include a reuqest reducer so you could keep track of the status of that request.

A good question would be do you care if performing that action fails?

**Comment by ccbrown** [comment]
Guess I'll probably do that after the other review gets some high level feedback then.

**Comment by ccbrown** [comment]
1-sntxfelfuqlsfdnvzkj6ia

But it seems to work, so maybe it's correct? I'm gonna have to read up more on Redux...

**Comment by ccbrown** [comment]
@enahum Do we have a way to mock the server or am I gonna have to make a test that actually creates an interactive post, starts up a local HTTP server for the integration, modifies the Mattermost config to disable the SSRF prevention, performs an action, then reverts the config change? Because that seems difficult. And this needs to be merged today...

**Comment by enahum** [comment]
@ccbrown there we are using nock to mock server requests you can take a look at other tests that use it

**Comment by ccbrown** [comment]
@enahum Thanks. I think I got it figured out. How's that?

**Comment by enahum** [comment]
@ccbrown well looks good but 2 things

1. I do not see any assertions being made
2. you have tests failures

1 failing

  1) Actions.Posts doPostAction:
     Error: doPostAction request failed
      at _callee31$ (test/actions/posts.test.js:1013:19)
      at tryCatch (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:117:21)
      at step (test/actions/posts.test.js:41:191)
      at test/actions/posts.test.js:41:361
      at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by jwilander** [comment]
@enahum I don't think he needs any assertions since there is nothing store in any reducer, I think running through the code and making sure the request is not marked a failure good enough

**Comment by ccbrown** [comment]
@enahum 

1. What kind of assertions do you think should be made? Neither the request nor response even have a body.

2. >_< It works fine on my machine and that's such a useless error message...

**Comment by enahum** [comment]
ok no need for assertions but at the very least lets fix the failing test and we can merge this

**Comment by ccbrown** [comment]
@enahum There we go.

**Pull request merged**
