### PR TITLE
MM-31882 - Add CodeQL check 

### PR DESCRIPTION
**Pull request by srkgupta**
#### Summary
Added step to run automated CodeQL checks. Once this file is merged, the codeql checks will automatically be performed on new pull requests to master branch.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-31882

### CODE REVIEW

**Comment by hahmadia** [comment]
Not gonna lie but I don't really feel I'm the appropriate one for checking this. Maybe @metanerd would be better?

**Comment by metanerd** [comment]
I guess this still needs the github webhooks to show the results? I would postpone my review then for the time being.

**Comment by srkgupta** [comment]
@metanerd that's a separate task I will be working on. This PR only runs the CodeQL on every pull-request, push or on scheduled cron time and alerts/results are generated and shown as one of the checks.

**Review by metanerd — APPROVED** [review]
Great job Rohitesh!

**Comment by srkgupta** [comment]
@mkraft can you please review this when you have a moment. Thanks.

**Review by mkraft — APPROVED** [review]

**Pull request merged**
