### PR TITLE
Moved getFlaggedPosts action from webapp to redux

### PR DESCRIPTION
**Pull request by lisakycho**
#### Summary
Moved getFlaggedPosts action to mattermost-redux

#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/8497

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Added or updated unit tests (required for all new features)

#### Test Information
This PR was tested on: macOS High Sierra

### CODE REVIEW

**Comment by enahum** [comment]
Hmmm this action already exists

https://github.com/mattermost/mattermost-redux/blob/master/src/actions/search.js#L88

**Comment by lisakycho** [comment]
@enahum Weird, the webapp doesn't seem to be using the getFlaggedPost from /seach.js and was still getting called from webapp actions. 
@jasonblais should I just changed the webapp to call this action from /search.js then?

**Comment by enahum** [comment]
The mobile app does, and I think the webapp should use that action instead

**Comment by jwilander** [comment]
Yeah if there's already an existing action we should use it but also update it to also do what your new action here does

**Comment by enahum** [comment]
@lisakycho just a follow up,  are you going to make the changes with @jwilander suggestion?

**Comment by enahum** [comment]
is this still something you want to push through @lisakycho ?

**Comment by lisakycho** [comment]
@enahum Sorry for the late reply! I won't be able to do this until at least after the summer!

**Pull request closed without merging**
