### PR TITLE
Changed the method to POST in removeRecentCustomStatus API call

### PR DESCRIPTION
**Pull request by chetanyakan**
#### Summary
- Changed the request type to POST for the remove recent custom status API

#### Ticket Link

Related PR: https://github.com/mattermost/mattermost-server/pull/17122

### CODE REVIEW

**Comment by nevyangelova** [comment]
Hello @chetanyakan do we have a green light from server team to merge this? If so this PR needs to wait for that PR to go in as well. Otherwise LGTM

**Review by nevyangelova — APPROVED** [review]

**Comment by hmhealey** [comment]
@chetanyakan We're going to be shortly deprecating mattermost-redux as a standalone repository and moving it into [mattermost-webapp](https://github.com/mattermost/mattermost-webapp) as part of an effort to make development of both codebases easier by using a monorepo. This is going to require either merging or closing all outstanding pull requests in this repository in preparation for the migration planned for tomorrow.

Since this is waiting on server changes, we'll probably have to close it and reopen in the webapp repo once that migration is done. I can help doing that if you'd like, but either way on that, I'll let you know when this can be reopened after that migration is done.

**Review by calebroseland — APPROVED** [review]

**Comment by hmhealey** [comment]
As mentioned above, I'm going to close this for now. We can continue testing the server changes with this branch for the time being, but I'll let you know when you can resubmit this against the webapp repo.

**Comment by hmhealey** [comment]
@chetanyakan Thanks for waiting on that. mattermost-redux now lives [here](https://github.com/mattermost/mattermost-webapp/tree/master/packages/mattermost-redux), so you can resubmit your changes over there.

**Pull request closed without merging**
